doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(resolve:DB_DATABASE)%'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '10.11.7-MariaDB'
        charset: utf8mb4

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            #App:
            #    type: attribute
            #    is_bundle: false
            #    dir: '%kernel.project_dir%/src/Entity'
            #    prefix: 'App\Entity'
            #    alias: App
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Domain'
                prefix: 'App\Auth\Domain'
                alias: Auth
            Customer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Customer/Domain'
                prefix: 'App\Customer\Domain'
                alias: Customer
            Order:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Domain'
                prefix: 'App\Order\Domain'
                alias: Order
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
